# Generated by Django 4.1 on 2022-10-16 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('tel_uno', models.CharField(max_length=10)),
                ('tel_dos', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=60)),
                ('company', models.CharField(max_length=100)),
                ('date_create', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
